### ISSUE TITLE
Server auto reset to default items after players changed their items

### ISSUE THREAD

**Issue by hoan111** [Natanel-Shitrit/MiscChanger#7] opened 2020-11-28 16:36 UTC
After I changed my default items after 2-3 rounds, the server auto-reset to my default items that I owned. I think this problem can come from the MySQL database. Please check again. No error log has been shown. 
Thank you for your hard work!

**Comment by Natanel-Shitrit** [comment] 2020-12-06 16:56
Hey,
First of all, sorry for the late response - I'm a-bit busy with school atm.
I have never encountered this kind of behavior from this plugin, so I will need a bit more information.

Can you include steps to preproduce this behavior?
The items reset always 2-3 rounds after changing your items?

Hope we can resolve this and thanks for reporting the issue,
Natanel.

**Comment by Jansel80** [comment] 2020-12-08 14:25
If I may add input, 

I am also dealing with this issue on my server where every 2-3 rounds the items reset (normally at the start of the round). This applies to both the music kits and the coins/badges. 

I select the music kit/badge. It works for a couple (2-3) rounds then it reverts to my real music kit/medal. 
It all works perfectly fine for the first 2 rounds after setting it up but after that, it reverts to default/real music kit.

**Comment by Natanel-Shitrit** [comment] 2020-12-08 17:26
Thank you for the additional input.
May I ask in what version does that happen?

**Comment by Jansel80** [comment] 2020-12-09 05:45
It occurs on the latest CS:GO update (12/7/2020) and the update before that (12/4/2020). I got both the latest eItems release (Broken Fang) and the latest pTaH build13 on the site.

**Comment by hoan111** [comment] 2020-12-09 06:24
Yes. Like @Jansel80  said. It occurred on the lastest CSGO update and before that. And after I changed the gamedata signature to your latest commit, the plugin didn't work anymore.
Error log:
L 12/08/2020 - 06:36:10: [SM] Exception reported: Failed to get CCSPlayer::SetRank signature
L 12/08/2020 - 06:36:10: [SM] Blaming: MiscChanger.smx
L 12/08/2020 - 06:36:10: [SM] Call stack trace:
L 12/08/2020 - 06:36:10: [SM]   [0] SetFailState
L 12/08/2020 - 06:36:10: [SM]   [1] Line 946, E:\csgo_server\csgosl\serverfiles\csgo\addons\sourcemod\scripting\MiscChanger.sp::LoadGameData
L 12/08/2020 - 06:36:10: [SM]   [2] Line 179, E:\csgo_server\csgosl\serverfiles\csgo\addons\sourcemod\scripting\MiscChanger.sp::OnPluginStart
L 12/08/2020 - 06:36:10: [SM] Unable to load plugin "MiscChanger.smx": Error detected in plugin startup (see error logs)

**Comment by Jansel80** [comment] 2020-12-15 11:05
No longer experiencing the issue. Not sure if it was due to the update or because I changed something in my database (from "mysql" to just default. Not sure what that would've done though).

Will update whether it occurs again or not.

**Comment by Natanel-Shitrit** [comment] 2020-12-15 11:35
The update pushed yesterday wasn't related to this issue nor anything with SQL so i guess it was something with older version that got resolved and you didn't update (?)

Anyway, if this happens again feel free to reopen this issue, as for now i will close this issue because i can't reproduce it.

**Closed as completed by Natanel-Shitrit** 2020-12-15 11:35 UTC
Labels: more info needed
